# Generated by Django 3.1.5 on 2021-02-09 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Wishlist',
        ),
    ]
